@startuml

interface Targetable{
    void method1();
    void method2();
}

class  Adapter{
    void method2();
}

class Client{

}

class Source{
    void method1();
}

Client ..> Targetable

Adapter ..o Targetable

Adapter ..|> Source

@enduml