@startuml

interface Eventable{
    void sender();
}

class EventSender{
    void sender();
}

class Proxy{
   void sender();
}

Eventable <|.. EventSender
Eventable <|.. Proxy

Client ..> Proxy

@enduml